### ISSUE TITLE
Centroids 초기값 함수 작성 

### ISSUE THREAD

**Issue by A-by-alimelon** [boostcamp-2020/Project17-C-Map#16]
- [x] 랜덤 값 추출 

- [x] 카메라 좌표 영역 균등 분할

- [ ] 데이터를 sorting 하여 중심 값
    => sorting 기준 설정 필요

**Comment by donggeonoh** [comment]
데이터 sorting 후 분할 방법은 분할하는 기준이 모호
또한 좋은 방법이 아님
