### ISSUE TITLE
Centroids  초기값 함수 작성: k-means++

### ISSUE THREAD

**Issue by A-by-alimelon** [boostcamp-2020/Project17-C-Map#17]
KMeans++ 알고리즘으로 초기 값 추출

**Comment by Seungeon-Kim** [comment]
KMeans++ 중심값 알고리즘에서 ballcut 알고리즘으로 변경 

랜덤 샘플링 시 계산이 많음 (Kmeans의 단점)
어느정도의 coverage distance가 보장됨 (ballcut 장점)
