### ISSUE TITLE
Map 기본 화면 설정

### ISSUE THREAD

**Issue by eunjeongS2** [boostcamp-2020/Project17-C-Map#2]
- [x] zoom level 지정

- [x] zoom in/out 버튼 추가

- [x] 나침반 추가

- [x] 축척바 추가

- [x] 현재위치버튼 추가

- [x] 현재 위치로 카메라 이동

- [x] 한반도로 카메라 범위 지정

**Comment by rnfxl92** [comment]
## 구현내용

### [feat] 
* 기본 ViewController의 이름을 MapViewController로 변경
* NMFNaverMapView를 상속받은 InteractiveMapView 생성 하여 초기 설정
    - Zoom 버튼, 현재위치 버튼, 나침반, 축척바 추가
    - Zoom 최소, 최대 설정
    - 한반도만 보이게 extent 설정

## 논의사항
현재 위치 버튼을 눌러도 실행되지 않음 -> 
CLLocationManager를 사용해서 해결 (locationManager.requestWhenInUseAuthorization())

### 화면
![스크린샷 2020-11-21 오후 6 18 01](https://user-images.githubusercontent.com/33716159/99873423-0e95a680-2c26-11eb-89bf-a4f99ebf8f7f.png)
