### ISSUE TITLE
QuadTreeNode 구현

### ISSUE THREAD

**Issue by rnfxl92** [boostcamp-2020/Project17-C-Map#20]
- [x] QuadTree Node Insert 구현
- [x] QuadTree Node regionQuery 구현
- [x] QuadTree Node Test 구현

**Comment by eunjeongS2** [comment]
## 구현내용
### [feat], [clustering], [test]
* insert(coordinate: Coordinate) 을 구현했습니다.

* findCoordinates(region: BoundingBox) 을 구현했습니다.

* updateBoundingBox() 을 구현했습니다.

* 테스트했습니다.
  - init
  - insert (만든QuadTree와 동일한지)
  - 범위 밖의 값 안들어가는지
  - findCoordinates
