### ISSUE TITLE
Core data 재설계

### ISSUE THREAD

**Issue by donggeonoh** [boostcamp-2020/Project17-C-Map#40]
데이터 구조에 따라 Core data relation 설계

**Comment by jaekyoungshin** [comment]
데이터 설계 내용은 어디에 있나요?

**Comment by donggeonoh** [comment]
@jaekyoungshin 안녕하세요 신재경 멘토님.
현재 Core data 관련하여 팀원들과 다시 설계 하려고합니다.
이후 issue에 게재 하겠습니다.
