### ISSUE TITLE
클러스터 마커 원 크기 결정

### ISSUE THREAD

**Issue by A-by-alimelon** [boostcamp-2020/Project17-C-Map#47]
클러스터 데이터의 개수에 맞춰 원의 크기를 조정할 때 적절한 크기 선정 필요

1. minimum 을 정해야 할 것
2. 클러스터 원 끼리 겹치는 것 조정 
3. 화면 줌 레벨 따라서 조정

**Comment by rnfxl92** [comment]
let r: CGFloat = 18 + CGFloat(2 * log2(Double(coordinatesCount)))
