### ISSUE TITLE
클러스터 마커 중복 찍힘 문제 

### ISSUE THREAD

**Issue by A-by-alimelon** [boostcamp-2020/Project17-C-Map#48]
클러스터 마커에 알파 값을 주고 찍었을 때 
몇몇 부분에서 색깔이 다른 것을 발견 -> 같은 클러스터가 겹쳐서 두번 찍힌 것으로 예상 

<img width="231" alt="스크린샷 2020-10-29 오전 12 29 12" src="https://user-images.githubusercontent.com/62557093/100847586-5b4d6d00-34c3-11eb-9e2d-eb84a8d8abfb.png">

**Comment by rnfxl92** [comment]
클러스터링 영역 문제로 y쪽에서 한칸더 클러스터링해서 생긴문제였음
