### ISSUE TITLE
클러스터 원 합치기

### ISSUE THREAD

**Issue by A-by-alimelon** [boostcamp-2020/Project17-C-Map#50]
클러스터 원이 겹쳐질 경우 할선을 이용하여 클러스터 두 개를 합칠 지 결정

**Comment by donggeonoh** [comment]
가시성을 위해 데이터의 결과를 가공하여서 클러스터를 다르게 표시하는 것에 대해 데이터 결과를 변질 하는 것이라는 피드백을 받음.
그래서 데이터의 결과 그대로 표현하도록 결정
