### ISSUE TITLE
지도에 삭제되지 않는 마커 있던 이슈

### ISSUE THREAD

**Issue by eunjeongS2** [boostcamp-2020/Project17-C-Map#51]
onTileChanged 이벤트가 많이 발생하는 경우 지워져야 할 마커 지워지지 않는다.

**Comment by Seungeon-Kim** [comment]
마커의 삭제와 생성의 순서가 보장이 되지않아 발생하던 문제, (생성전 삭제를 요청하여 정상적으로 삭제가 않던 현상)

생성전 삭제되는 마커들을 임시로 저장하여, 순서를 조율
