### ISSUE TITLE
맨 처음 시작할 때 마커 안나오는 문제

### ISSUE THREAD

**Issue by A-by-alimelon** [boostcamp-2020/Project17-C-Map#63]
첫 시작 때 onTileChange 이벤트가 안불리는 것 같은데 
확인 해봐야 할 것 같습니다

**Comment by Seungeon-Kim** [comment]
이벤트는 불리는데 처음 트리만들고 바로 렌더링이 안되고 다음 이벤트일 때 만들어진 트리로 보여지는걸로 지금 되어있을 거에요.
이부분은 수정을 해야합니다 ㅎㅎ..ㅠㅠ

**Comment by eunjeongS2** [comment]
DispatchGroup을 이용해서 클러스터링 작업들을 저장해놨다가 트리가 만들어지면 클러스터링을 수행하도록 수정했습니다.
