### ISSUE TITLE
클러스터 클릭시 카메라 이동 동작 버그

### ISSUE THREAD

**Issue by Seungeon-Kim** [boostcamp-2020/Project17-C-Map#77]
- 클러스터 마크 클릭시, 카메라가 반대로 이동하는 버그

![ezgif com-gif-maker](https://user-images.githubusercontent.com/57888770/101454260-02268300-3974-11eb-857e-e36a5cfd8db5.gif)

**Comment by rnfxl92** [comment]
데이터가 많은 경우 무조건 줌레벨 2를 상승시키는 것으로 변경
