### ISSUE TITLE
마커 레이어 메모리 릭!

### ISSUE THREAD

**Issue by Seungeon-Kim** [boostcamp-2020/Project17-C-Map#99]
마커 레이어 메모리 릭 이슈

![스크린샷 2020-12-13 오전 4 00 16](https://user-images.githubusercontent.com/57888770/101992593-de5a9880-3cf7-11eb-9a4d-a9e579852893.png)
![스크린샷 2020-12-13 오전 4 03 38](https://user-images.githubusercontent.com/57888770/101992636-31cce680-3cf8-11eb-954f-369045bc5ac9.png)

**Comment by eunjeongS2** [comment]
카메라 이벤트에서 레이어를 지워서 해결
